application: coursearcher
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: html/css

- url: /.*
  script: coursearcher.application

libraries:
- name: jinja2
  version: latest
